chore: take out confusing extra pages
twilio-labs/paste-prototype-kit pull request #18
Opened 2021-02-02 18:03 UTC by gloriliale

Eliminate 'Explore Products' and 'Active Numbers' pages from kit; they added to general confusion

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2021-02-02 18:50 UTC, nkrantz approved these changes
Looks great!

2021-02-03 01:53 UTC, SiTaggart requested changes
Should these also be removed from the side nav?

2021-02-03 17:18 UTC, gloriliale commented
> Should these also be removed from the side nav?

@SiTaggart they absolutely should. Done!

2021-02-03 18:30 UTC, SiTaggart approved these changes

2021-02-03 21:35 UTC, merged